apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.22.3
      helm:
        valueFiles:
          - $values/values/istio-ingress-values.yaml
    - repoURL: https://github.com/jaiganesh/gitops-istio
      targetRevision: main
      ref: values
      parameters: []
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
    createNamespace: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }
